### ISSUE TITLE
--csv-full-history throws error when in master/slave mode

### ISSUE THREAD

**Issue by uprichard** [locustio/locust#1202]
Steps:
Start a test in master/slave mode ie.
locust -f test.py --no-web --host http://example.com -t 10  --csv-full-history --csv master --master
Then start a slave
locust -f test.py --no-web --host http://example.com  --slave

Error:
Following exception is listed twice

> [2019-12-20 12:31:58,477] me/ERROR/stderr: Traceback (most recent call last):
[2019-12-20 12:31:58,477] me/ERROR/stderr: 
[2019-12-20 12:31:58,477] me/ERROR/stderr: File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
[2019-12-20 12:31:58,477] me/ERROR/stderr: 
[2019-12-20 12:31:58,477] me/ERROR/stderr: File "/Users/me/PythonVersions/locust/lib/python3.7/site-packages/locust/stats.py", line 763, in stats_writer
    write_stat_csvs(base_filepath, stats_history_enabled)
[2019-12-20 12:31:58,477] me/ERROR/stderr: 
[2019-12-20 12:31:58,477] me/ERROR/stderr: File "/Users/me/PythonVersions/locust/lib/python3.7/site-packages/locust/stats.py", line 773, in write_stat_csvs
    f.write(stats_history_csv(stats_history_enabled) + "\n")
[2019-12-20 12:31:58,477] me/ERROR/stderr: 
[2019-12-20 12:31:58,477] me/ERROR/stderr: File "/Users/me/PythonVersions/locust/lib/python3.7/site-packages/locust/stats.py", line 887, in stats_history_csv
    str(int(s.get_current_response_time_percentile(x) or 0)) for x in PERCENTILES_TO_REPORT])
[2019-12-20 12:31:58,477] me/ERROR/stderr: 
[2019-12-20 12:31:58,477] me/ERROR/stderr: File "/Users/me/PythonVersions/locust/lib/python3.7/site-packages/locust/stats.py", line 887, in <listcomp>
    str(int(s.get_current_response_time_percentile(x) or 0)) for x in PERCENTILES_TO_REPORT])
[2019-12-20 12:31:58,478] me/ERROR/stderr: 
[2019-12-20 12:31:58,478] me/ERROR/stderr: File "/Users/me/PythonVersions/locust/lib/python3.7/site-packages/locust/stats.py", line 511, in get_current_response_time_percentile
    raise ValueError("StatsEntry.use_response_times_cache must be set to True if we should be able to calculate the _current_ response time percentile")
[2019-12-20 12:31:58,478] me/ERROR/stderr: 
[2019-12-20 12:31:58,478] me/ERROR/stderr: ValueError: StatsEntry.use_response_times_cache must be set to True if we should be able to calculate the _current_ response time percentile
[2019-12-20 12:31:58,478] me/ERROR/stderr: 
[2019-12-20 12:31:58,478] me/ERROR/stderr: 2019-12-20T20:31:58Z
[2019-12-20 12:31:58,478] me/ERROR/stderr: 
[2019-12-20 12:31:58,478] me/ERROR/stderr: <Greenlet at 0x10b0b6ef0: stats_writer('master', True)> failed with ValueError

**Comment by pelanmar1** [comment]
I'm having the same problem. Did you come up with anything?

**Comment by pelanmar1** [comment]
I think I fixed it running:
- master node with the  --no-web and --csv option (and no --csv-full-history)
- slave node with only the --no-web and --csv-full-history options.

I'm using docker swarm so for me it was:
```
locust_master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master
      LOCUST_OPTS: --csv=/locustio/tests/temp --expect-slaves 5 --no-web -c 50 -r 1 --logfile=/locustio/tests/logs --print-stats --reset-stats
  
  locust_slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER_HOST: locust_master
      LOCUST_OPTS:  --no-web --csv-full-history --reset-stats
    deploy:
      replicas: 5
```
