### ISSUE TITLE
Docker image: worker mode not starting correctly

### ISSUE THREAD

**Issue by liliankasem** [locustio/locust#1322]
### Describe the bug
When running the latests docker image with `LOCUST_MODE` set to `worker`, locust should start in worker mode, but it does not.

It seems to start in standalone mode and the correct `LOCUST_OPTS` from the `docker_start.sh` file are not being set.

### Expected behavior
When the container runs, I should see:

```
Starting Locust in worker mode...
$ locust  -f /tests/locustfile.py -H ${TARGET_URL} --worker --master-host=${LOCUST_MASTER_HOST} --master-port=${LOCUST_MASTER_PORT:-5557}
```
Line 19 in the docker file should take effect:
https://github.com/locustio/locust/blob/master/docker_start.sh

### Actual behavior
It seems to recognise that the mode was set to worker, but the options are not getting updated to run in worker mode:

```
Starting Locust in worker mode...
$ locust  -f /tests/locustfile.py -H http://something
[2020-04-10 06:05:33,874] moma-locust-worker-c8m79/INFO/locust.main: Starting web monitor at http://*:8089
[2020-04-10 06:05:33,874] moma-locust-worker-c8m79/INFO/locust.main: Starting Locust 0.14.5
```

### Steps to reproduce
Run the docker image with these environment variables set

```
      LOCUST_MODE:         worker
      LOCUST_MASTER_HOST:  something
      TARGET_URL:          http://something
      LOCUSTFILE_PATH:     /tests/locustfile.py
```

### Environment

- OS: docker
- Python version: official locust docker image (latest)
- Locust version: 0.14.5

This docker-compose give the same issue:
```
x-common: &common
  image: locustio/locust
  environment: &common-env
    TARGET_URL: http://localhost:8080
    LOCUSTFILE_PATH: /tests/locustfile.py
  volumes:
    - ./tests:/tests

services:
  locust-master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master

  locust-worker:
    <<: *common
    depends_on: [locust-master]
    environment:
      <<: *common-env
      LOCUST_MODE: worker
      LOCUST_MASTER_HOST: locust-master
```
