### ISSUE TITLE
locust status ready but 0 users

### ISSUE THREAD

**Issue by 4ss3g4f** [locustio/locust#1544]
Locust docker installed and working, but when executed there is no users ??

![image](https://user-images.githubusercontent.com/22811935/91237877-f79a0200-e765-11ea-96b9-f0fbe54054af.png)

### Describe the bug
no users running for test

### Expected behavior
 users should be not 0 (zero)

```
version: '3.7'

networks:
  bridge:
    external: true

services:
  master:
    image: locustio/locust:latest
    deploy:
      replicas: 1
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
     - "8089:8089"
    networks:
      - bridge
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://192.168.33.231:8089
    
  worker:
    image: locustio/locust:latest
    networks:
      - bridge
    deploy:
      replicas: 3
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host 192.168.33.231:8089
```

I copy all files from https://github.com/locustio/locust/tree/master/examples to the docker yaml volume path,
and change ip 127.0.0.1 to 192.68.33.231

![image](https://user-images.githubusercontent.com/22811935/91238051-50699a80-e766-11ea-8c2c-f99aa4561b21.png)

Why locust is not running ??

**Comment by cyberw** [comment]
Have you checked the log (command line output) for master and workers?

**Comment by max-rocket-internet** [comment]
I think you're making this too complicated. Here's my `docker-compose.yml`:

```yaml

version: '3'

services:
  master:
    image: locustio/locust:1.2
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
      - ./locust:/usr/local/lib/python3.8/site-packages/locust
    command: -f /mnt/locust/locustfile.py --master -H http://target
    # command: -f /mnt/locust/locustfile.py --master -H http://target --step-load

  worker:
    image: locustio/locust:1.2
    volumes:
      - ./:/mnt/locust
      # - ./locust:/usr/local/lib/python3.8/site-packages/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --loglevel DEBUG

  target:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d/
```

Then to start with with 3 workers: `docker-compose up --scale worker=3`

**Comment by 4ss3g4f** [comment]
@max-rocket-internet ,

Whats is the value of http://target ??
is it locust master node ip and port or it is the target domain which is going to be stresstest with locust ??

**Comment by max-rocket-internet** [comment]
> Whats is the value of http://target ??

That's the container named `target`, it's in the YAML. You can use container names as hostnames in docker-compose. This container is the target of the load test.

**Comment by solxnp** [comment]
I also encountered this problem in version 1.2.2, but the same code works fine in version 1.1.1

**Comment by max-rocket-internet** [comment]
> users should be not 0 (zero)

Your user count is 0 because your worker is not connected. You can see it `Workers 0` in the screen shot. You should debug network communication between your workers and master.

**Comment by 4ss3g4f** [comment]
@cyberw ,

Here are the master and worker logs from portainer,

![image](https://user-images.githubusercontent.com/22811935/91648128-faf6fb80-ea8d-11ea-8f42-4ba4b82c7393.png)

![image](https://user-images.githubusercontent.com/22811935/91648135-077b5400-ea8e-11ea-89f0-50b7f174f13b.png)

@max-rocket-internet ,

yes i think you are right

```
version: '3.7'

networks:
  bridge:
    external: true

services:
  master:
    image: locustio/locust:latest
    deploy:
      replicas: 1
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
     - "8089:8089"
    networks:
      - bridge
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://www.google.com
    
  worker:
    image: locustio/locust:latest
    networks:
      - bridge
    deploy:
      replicas: 3
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
```
it should be connected between master and worker, i will check again. Thank you

**Comment by 4ss3g4f** [comment]
Guys, thank you very much. locust is running properly now

![image](https://user-images.githubusercontent.com/22811935/91648501-dd786080-ea92-11ea-8cfb-5a9a007b2913.png)

![image](https://user-images.githubusercontent.com/22811935/91648506-e832f580-ea92-11ea-889e-b4203ea28489.png)

```
version: '3.7'

networks:
  bridge:
    external: true

services:
  master:
    image: locustio/locust:latest
    deploy:
      replicas: 1
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
     - "8089:8089"
     - "5557:5557"
    networks:
      - bridge
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://www.google.com
    
  worker:
    image: locustio/locust:latest
    networks:
      - bridge
    ports:
     - "5558:5558"
    deploy:
      replicas: 3
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    depends_on:
      - master
    volumes:
      - /home/core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host=192.168.33.230
```
