### ISSUE TITLE
Connection status for workers in distributed mode

### ISSUE THREAD

**Issue by parberge** [locustio/locust#1571]
When locust runs in `--worker` mode it doesn't say anything about the connection to master.
This can be hard to debug when the workers can't connect to the master, because it doesn't validate the connection at all.

### Describe the solution you'd like

A log message for the workers saying that it's connected via tcp://1.2.3.4 etc, and that it should fail if connection doesn't work, or at least print a warning/error message about it.

**Comment by parberge** [comment]
Actually I think this should be a bug.

This code here https://github.com/locustio/locust/blob/96d24d6b65059d21f9b3232aa97306e435747b97/locust/main.py#L240 suggest that it should fail if the connection doesn't work.

However using this docker-compose as en example you'll never get any connection errors, even though it should:

docker compose:
```
version: '3'

services:
  master:
    image: locustio/locust:1.2.3
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust:1.2.3
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master --master-port 8080
```

Result:

```
master_1  | [2020-10-01 07:15:42,265] 4289a6670371/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
worker_1  | [2020-10-01 07:15:42,268] 81d841ea70f2/INFO/locust.main: Starting Locust 1.2.3
master_1  | [2020-10-01 07:15:42,304] 4289a6670371/INFO/locust.main: Starting Locust 1.2.3
```
And as expected the master never reports any connected worker.
