### ISSUE TITLE
MasterRunner target_user_count no longer set for test_start event listeners

### ISSUE THREAD

**Issue by jrweldon** [locustio/locust#1883]
### Describe the bug
I was following the `custom_messages.py` example and noticed that `environment.runner.target_user_count` is no longer resolving to the number of users being created for the test. This functionality appears to have been broken between tags `2.0.0b1` and `2.0.0b2`.

### Expected behavior
The MasterRunner's `target_user_count` should resolve to the number of users specified in the WebUI for the test.
The `custom_messages.py` example for a test with 10 users and 2 workers should log a message from each worker indicating that they received 5 users.
```
master_1  | [2021-09-14 02:48:02,550] d4b6940eebd0/INFO/locust.runners: Sending spawn jobs of 10 users at 1.00 spawn rate to 2 ready clients
master_1  | Thanks for the 5 users!
master_1  | Thanks for the 5 users!
worker_1  | User4
worker_2  | User9
worker_1  | User3
...
```

### Actual behavior
The MasterRunner's `target_user_count` is 0, causing numerous exceptions in the `custom_messages.py` example.
```
master_1  | [2021-09-14 03:01:33,449] 0134f51ea2b2/INFO/locust.runners: Sending spawn jobs of 10 users at 1.00 spawn rate to 2 ready clients
master_1  | Thanks for the 0 users!
master_1  | Thanks for the 0 users!
worker_2  | Traceback (most recent call last):
worker_2  |   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
worker_2  |   File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 1138, in <lambda>
worker_2  |     self.spawning_greenlet = self.greenlet.spawn(lambda: self.start_worker(job["user_classes_count"]))
worker_2  |   File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 1075, in start_worker
worker_2  |     self.spawn_users(user_classes_spawn_count)
worker_2  |   File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 221, in spawn_users
worker_2  |     new_users += spawn(user_class, spawn_count)
worker_2  |   File "/usr/local/lib/python3.8/site-packages/locust/runners.py", line 210, in spawn
worker_2  |     new_user = self.user_classes_by_name[user_class](self.environment)
worker_2  |   File "/mnt/locust/custom_messages.py", line 55, in __init__
worker_2  |     self.username = usernames.pop()
worker_2  | IndexError: pop from empty list
worker_2  | 2021-09-14T03:01:33Z <Greenlet at 0x7fc070a7ae10: <lambda>> failed with IndexError
...
```

### Steps to reproduce
1. Create `docker-compose.yml`:
```yaml
version: '3'

services:
  master:
    image: locustio/locust:2.2.1
    # image: locustio/locust:2.0.0b1 ## Last known working version
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/custom_messages.py --master -H http://master:8089
  
  worker:
    image: locustio/locust:2.2.1
    # image: locustio/locust:2.0.0b1 ## Last known working version
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/custom_messages.py --worker --master-host master
    deploy:
      mode: replicated
      replicas: 2
```
2. Copy the existing [examples/custom_messages.py](https://raw.githubusercontent.com/locustio/locust/master/examples/custom_messages.py) into the same directory as the `docker-compose.yml`
3. Run `docker compose up`
4. Visit http://localhost:8089/ and start a test with 10 users
5. (Optional) Modify the `docker-compose.yml` to use a different image tag listed below and repeat steps 3 and 4.

### Environment

- OS: `Debian GNU/Linux 11 (bullseye)` from `locustio/locust` docker image.
- Python version: `3.8.11` and `3.8.12` from the various `locustio/locust` docker images.
- Locust version: `2.0.0b2`, `2.0.0b3`, `2.1.0`, `2.2.0`, `2.2.1`
- Locust command line that you ran: See `docker-compose.yml` above.
- Locust file contents (anonymized if necessary): [examples/custom_messages.py](https://raw.githubusercontent.com/locustio/locust/master/examples/custom_messages.py)
