### ISSUE TITLE
Stats CSV is overwritten on autoquit

### ISSUE THREAD

**Issue by jjrm** [locustio/locust#1998]
### Describe the bug
The Stats CSV is overwritten with just the header information after the locust process exits.  Prior to the process exiting, the Stats CSV contain the proper information (see screenshots below).  Before Autoquit, the size of results_stats.csv is 471B, after it is down to 290B.  Upon inspection, the CSV is overwritten with just the header information.

Prior to Autoquit
![image](https://user-images.githubusercontent.com/11521672/152565144-94c0bef7-fafc-47b1-9bd6-89a86a20b9fc.png)

After Autoquit
![image](https://user-images.githubusercontent.com/11521672/152565256-a61f1bee-6a0f-4bac-b71f-431c738416ef.png)

### Expected behavior
Stats CSV should not be overwritten.

### Actual behavior
Stats CSV is overwritten.

### Steps to reproduce
Deploy Locust test using the Delivery Hero Helm charts.

### Environment
Using Delivery Hero Helm Charts for Locust (AKS)

```
image:
  tag: "2.7.2"

master:
  args: ["--autostart", "--autoquit", "180", "-u", "1", "-r", "1", "-t", "120s", "--expect-workers", "1", "--csv", "/mnt/locust/results/results"]
```
