### ISSUE TITLE
command line options parsed incorrectly

### ISSUE THREAD

**Issue by VetchM** [locustio/locust#2203]
### Describe the bug

I'm trying to use following `docker-compose` file to run headless mode locust, but every time i ran i got error: `/ERROR/locust.main: Unknown User(s)`. It used to work when i using `docker-compose` file in the docs(https://docs.locust.io/en/stable/running-in-docker.html?#docker-compose)
```yaml
version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - /home/load-test/locust:/mnt/locust
    command: -f /mnt/locust/${LOCUST_FILE} \
             -H ${LOAD_HOST} \
             --headless \
             --users 1000 \
             --spawn-rate 10 \ 
             --run-time 30m \
             --master \
             --html /mnt/locust/${NODE}.html \
             --stop-timeout 99 \
             ${NODE}

  worker:
    image: locustio/locust
    volumes:
      - /home/load-test/locust:/mnt/locust
    command: -f /mnt/locust/${LOCUST_FILE} --worker --master-host master
```
### Expected behavior

Running correctly

### Actual behavior

```python
/ERROR/locust.main: Unknown User(s):  --run-time,  --headless,  --stop-timeout,  --spawn-rate,  Test_node,  -H, 30m, /mnt/locust/Test_node.html, 10,  --master,  --users,  --html, 99, 1000, http://localhost:7554
```

The order of options is different every time i ran:

```python
/ERROR/locust.main: Unknown User(s): 99, http://localhost:7554, 30m,  --stop-timeout,  --html,  --spawn-rate,  Test_node,  --headless,  --users,  -H,  --master, 10, /mnt/locust/Test_node.html,  --run-time, 1000
```
### Steps to reproduce
 
Using above`docker-compose` file with this cmd:
` LOCUST_FILE=locustfile.py LOAD_HOST=http://localhost:7554 NODE=Test_node docker-compose up`
### Environment

- OS: Linux version 5.4.0-109-generic (buildd@ubuntu) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1))
- Python version: Python 3.9.13
- Locust version: locust 2.11.1
- Locust command line that you ran: 
- Locust file contents (anonymized if necessary):

**Comment by mikenester** [comment]
I was getting a similar error when (incorrectly) trying to pass in multiple locustfiles, separated by spaces instead of commas

Running: `locust -f locustfiles/locustfile1.py locustfiles/more/locustfile2.py`

Caused: `ERROR/locust.main: Unknown User(s): locustfiles/more/locustfiles2.py`

Have you tried keeping the `master` command to a single line, as a workaround?

**Comment by JOHNykn** [comment]
> I was getting a similar error when (incorrectly) trying to pass in multiple locustfiles, separated by spaces instead of commas
> 
> Running: `locust -f locustfiles/locustfile1.py locustfiles/more/locustfile2.py`
> 
> Caused: `ERROR/locust.main: Unknown User(s): locustfiles/more/locustfiles2.py`
> 
> Have you tried keeping the `master` command to a single line, as a workaround?

What do you mean by that? Can you show an example

**Comment by mikenester** [comment]
What I'm thinking could be a fix here is, in `docker-compose.yml`, instead of this:
```
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - /home/load-test/locust:/mnt/locust
    command: -f /mnt/locust/${LOCUST_FILE} \
             -H ${LOAD_HOST} \
             --headless \
             --users 1000 \
             --spawn-rate 10 \ 
             --run-time 30m \
             --master \
             --html /mnt/locust/${NODE}.html \
             --stop-timeout 99 \
             ${NODE}
```

try:
```
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - /home/load-test/locust:/mnt/locust
    command: -f /mnt/locust/${LOCUST_FILE} -H ${LOAD_HOST} --headless --users 1000 --spawn-rate 10 --run-time 30m --master --html /mnt/locust/${NODE}.html --stop-timeout 99 ${NODE}
```
