### ISSUE TITLE
Switch from Poetry to uv

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#3033]
### Prerequisites

- [x] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [x] I am suggesting a new feature, not asking a question

### Description

Poetry is too slow and cumbersome. And the whole community seems to be moving over as well.

I _think_ we could also remove `tox` while we are at it.

Here's some inspiration from locust-cloud.

```
...
[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = [
    "locust_cloud/**/*"
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.hooks.custom]
[tool.hatch.build.targets.BuildFrontend.hooks.custom]
...
```

```
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - uses: astral-sh/setup-uv@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - uses: astral-sh/setup-uv@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: uv venv --python 3.11
      # any local changes would make hatch-vcs set a "local version" (+dev0...), so we ignore any uv.lock updates:
      - run: git update-index --assume-unchanged uv.lock
      - run: python -m unittest discover []
```

`hatch_build.py` in root folder:

```
import subprocess

from hatchling.builders.hooks.plugin.interface import BuildHookInterface  # type: ignore


class BuildFrontend(BuildHookInterface):
    def initialize(self, version, build_data):
        try:
            subprocess.check_output("yarn install", cwd="locust/webui", shell=True, stderr=subprocess.STDOUT)
            subprocess.check_output("yarn build", cwd="locust/webui", shell=True, stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"'{e.cmd}' got exit code {e.returncode}: {e.output}")

        return super().initialize(version, build_data)
```
