### ISSUE TITLE
--master-host only accepts ipv4 formatted strings

### ISSUE THREAD

**Issue by ginonott** [locustio/locust#835]
### Description of issue / feature request

When setting up a distributed setup via docker-compose, I'd like to set the `master-host` to the locust_master service name. However, it seems that non-ipv4 formatted strings cause an error and crashes the slave. This is an example of what I would like to do (but causes the slave to crash with a ZMQError):
```
services:
version: '2.1'
services:
  locust_master:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - '.:/src'
    command:
      'locust'

  locust_workers:
    build: .
    command:
      'locust  --slave --master-host=locust_master'
    depends_on:
      - locust_master
```

### Expected behavior

It connects to the host via it's alias'ed hostname.

### Actual behavior

It crashes with a ZMQError

### Environment settings (for bug reports)

- OS: Red Hat Enterprise Linux 7
- Python version: 2.7
- Locust version: Stable

### Steps to reproduce (for bug reports)
Create a dockerfile with locust and then try to bring up a master / slave where `--master-host` is set to `locust_master`

**Comment by ginonott** [comment]
In case anyone else is also having this issue, the current work-around is to create a custom network and fix the locust_master ip address and set the slave's to use that fixed ipv4 address. Here is an example:
```
version: '2.1'
services:
  locust_master:
    build: .
    command:
      'locust'
    networks:
      locust_net:
        ipv4_address: 172.16.238.10

  locust_workers:
    build: .
    command:
      'locust --slave --master-host=172.16.238.10'
    depends_on:
      - locust_master
    networks:
      - locust_net
   
networks:
  locust_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
```
